
mybatis-plus:
  configuration:
#    记录mybatis查询
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 是否需要配置？？
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cj.mybatis.studyproject01.entity

# 数据源配置
#1.单数据源配置
#spring:
#  datasource:
#    url: jdbc:mysql://172.20.1.117:3306/mybatis_study_01?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: wqn
#    password: wqn641214
#    driver-class-name: com.mysql.cj.jdbc.Driver

#2.多数据源配置
spring:
  datasource:
    dynamic:
#      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        db1:
          url: jdbc:mysql://172.20.1.117:3306/mybatis_study_01?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: wqn
          password: wqn641214
#          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        db2:
          url: jdbc:mysql://172.20.1.118:3306/miniprogram?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
          username: wqn
          password: wqn641214
      lazy: true #采用懒加载模式，启动时不会报错，只有执行搜索时会出现报错
#          driver-class-name: com.mysql.jdbc.Driver
#        slave_2:
#          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
#          username: ENC(xxxxx)
#          password: ENC(xxxxx)
#          driver-class-name: com.mysql.jdbc.Driver